# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dorling_cartogram_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(518, 320)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 30, 91, 16))
        self.label.setObjectName("label")
        self.PushButtonOk = QtWidgets.QPushButton(Dialog)
        self.PushButtonOk.setGeometry(QtCore.QRect(270, 280, 113, 32))
        self.PushButtonOk.setObjectName("PushButtonOk")
        self.PushButtonCancel = QtWidgets.QPushButton(Dialog)
        self.PushButtonCancel.setGeometry(QtCore.QRect(390, 280, 113, 32))
        self.PushButtonCancel.setObjectName("PushButtonCancel")
        self.comboBoxLayer = QtWidgets.QComboBox(Dialog)
        self.comboBoxLayer.setGeometry(QtCore.QRect(170, 20, 321, 32))
        self.comboBoxLayer.setObjectName("comboBoxLayer")
        self.comboBoxField = QtWidgets.QComboBox(Dialog)
        self.comboBoxField.setGeometry(QtCore.QRect(170, 70, 321, 32))
        self.comboBoxField.setObjectName("comboBoxField")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 120, 61, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 160, 131, 16))
        self.label_5.setObjectName("label_5")
        self.doubleSpinBoxFriction = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBoxFriction.setGeometry(QtCore.QRect(180, 120, 62, 22))
        self.doubleSpinBoxFriction.setMaximum(1.0)
        self.doubleSpinBoxFriction.setSingleStep(0.01)
        self.doubleSpinBoxFriction.setProperty("value", 0.25)
        self.doubleSpinBoxFriction.setObjectName("doubleSpinBoxFriction")
        self.doubleSpinBoxRatio = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBoxRatio.setGeometry(QtCore.QRect(180, 160, 62, 22))
        self.doubleSpinBoxRatio.setMaximum(1.0)
        self.doubleSpinBoxRatio.setSingleStep(0.01)
        self.doubleSpinBoxRatio.setProperty("value", 0.4)
        self.doubleSpinBoxRatio.setObjectName("doubleSpinBoxRatio")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(30, 200, 131, 16))
        self.label_6.setObjectName("label_6")
        self.mQgsSpinBoxIterations = QgsSpinBox(Dialog)
        self.mQgsSpinBoxIterations.setGeometry(QtCore.QRect(180, 200, 90, 27))
        self.mQgsSpinBoxIterations.setMinimum(1)
        self.mQgsSpinBoxIterations.setMaximum(10000)
        self.mQgsSpinBoxIterations.setProperty("value", 200)
        self.mQgsSpinBoxIterations.setObjectName("mQgsSpinBoxIterations")

        self.retranslateUi(Dialog)
        self.PushButtonOk.clicked.connect(Dialog.accept) # type: ignore
        self.PushButtonCancel.clicked.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Compute Dorling cartogram"))
        self.label.setText(_translate("Dialog", "Input layer"))
        self.PushButtonOk.setText(_translate("Dialog", "Ok"))
        self.PushButtonCancel.setText(_translate("Dialog", "Cancel"))
        self.label_2.setText(_translate("Dialog", "Field"))
        self.label_4.setText(_translate("Dialog", "Friction"))
        self.label_5.setText(_translate("Dialog", "Ratio (Attraction %)"))
        self.label_6.setText(_translate("Dialog", "Iterations"))
from qgsspinbox import QgsSpinBox
